Добавил управление аккаунтом
urfu-2016/team2 pull request #126
Opened 2017-05-14 18:48 UTC by nikitc

2017-05-14 19:06 UTC, SemyonMakhaev requested changes

2017-05-14 19:06 UTC, SemyonMakhaev commented on app/controllers/account.js
> +        console.log(req.body);
Логгирование

2017-05-14 19:06 UTC, SemyonMakhaev commented
В остальном всё ништяк

2017-05-14 19:10 UTC, SemyonMakhaev approved these changes

2017-05-14 19:13 UTC, merged

2017-05-15 16:16 UTC, kol9nus commented
👍