Добавил webpack и конфиг к нему и stylus
urfu-2016/team2 pull request #46
Opened 2017-03-25 13:40 UTC by nikitc

2017-03-25 19:44 UTC, SemyonMakhaev requested changes
Никита, молодец, что подключил webpack и stylus. Хорошо, что разобрался, как webpack работает на примерах. Только давай всё-таки наверное не будем вливать эти примеры в продакшн :) Я говорю о папках eample1 и example2
И ты загрузил файл npm-dubug.log. Наверное имеет смысл добавить его в gitignore

2017-03-25 19:55 UTC, SemyonMakhaev commented
#44

2017-03-26 06:48 UTC, SemyonMakhaev approved these changes
Супер!

2017-03-26 06:48 UTC, merged

2017-03-27 06:35 UTC, kol9nus commented on package.json
> +    "eslint": "3.17.1",
А зачем ты линтер сюда впихнул? Он же есть в devDependencies.

2017-03-27 06:37 UTC, nikitc commented on package.json
> +    "eslint": "3.17.1",
Сорян, чуть позже выпилю