Правки верстки страницы квестов
urfu-2016/team2 pull request #84
Opened 2017-04-16 13:57 UTC by dkondrashin

2017-04-16 14:05 UTC, kol9nus requested changes

2017-04-16 14:05 UTC, kol9nus commented on app/controllers/quests.js
> +    console.log('hello');
Думаю, оно тут лишнее)

2017-04-16 14:05 UTC, kol9nus commented on app/controllers/quests.js
> +    const pattern = req.body.pattern.replace(forbiddenSearch, '');
Тут req.query наверн надо)

2017-05-11 13:05 UTC, SemyonMakhaev requested changes
Всё здорово! Нужна пара небольших правок, но главное, что всё работает :)

2017-05-11 13:05 UTC, SemyonMakhaev commented on desktop.ini
> +[ViewState]
Этот файл для чего?
Я полагаю, его надо добавить в .gitignore

2017-05-11 13:05 UTC, SemyonMakhaev commented on app/views/blocks/search/__input/search__input.html
> +<form action="/quests/search" method="GET" class="search__input-form">
Круто! Молодец, что разобрался

2017-05-11 13:05 UTC, SemyonMakhaev commented on app/views/blocks/quests-set/quest/__name/quest__name.html
> +<div class="name">{{name}}</div>
Это html-файл, а ты используешь в нём синтаксис handlebars.
Вообще, мы протестировали код в твоём форке, и переменная name, что удивительно, рендерится нормально. Но всё же будет лучше поменять расшрение файла на .hbs

2017-05-12 02:56 UTC, SemyonMakhaev approved these changes

2017-05-12 05:16 UTC, kol9nus approved these changes

2017-05-12 05:16 UTC, merged